max_width = 100
hard_tabs = false
tab_spaces = 4
array_width = 80
chain_width = 80
single_line_if_else_max_width = 50
newline_style = "Unix"
# Note: this has to be consistent with Cargo.toml's `edition`, otherwise `rustfmt` and `cargo fmt`
# will behave differently.
edition = "2024"

match_arm_leading_pipes = "Preserve"
